#! /bin/sh

# Startup Background
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends --backend glx -b &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon & 
emacs --daemon &
xiccd &

# Custome scirpts
sh $HOME/.local/bin/dock.sh &
sh $HOME/.local/bin/timer-checkupdates.sh &
pgrep bspswallow || $HOME/.local/bin/bspswallow &

# Startup applicaitons
nitrogen --restore
google-chrome-stable &
Alacritty &
spotify &
source $HOME/.config/env

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        	1
bspc config window_gap          	3

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	true
bspc config single_monocle	 	true
bspc config focused_border_color 	\#a9b3c2
bspc config normal_border_color 	\#111824
# bspc config initial_polarity 		first_child
bspc config automatic_scheme 		longest_side

bspc config pointer_modifier 		control
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_sidie

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

#emacs start in tilted
bspc rule -a Emacs state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a google-chromee desktop='^1' follow=on 
# bspc rule -a Alacritty desktop='^2' follow=on
# bspc rule -a newsboat desktop='^4' follow=on state=pseudo_tiled
# bspc rule -a Vim desktop='^5' follow=on state=pseudo_tiled
bspc rule -a Zathura desktop='^6' follow=on state=pseudo_tiled
# bspc rule -a Sxiv desktop='^6' follow=off 
# bspc rule -a Gimp desktop='^7' state=floating 
bspc rule -a discord desktop='^9' follow=off  

# bspc rule -a mpv focus=off state=floating
# bspc rule -a scratchpad locked=on sticky=on state=floating hidden=on
# bspc rule -a lf locked=on sticky=on state=floating hidden=on

# bspc rule -a Surf state=pseudo_tiled
# bspc rule -a Dragon-drag-and-drop locked=on sticky=on 
# bspc rule -a cool-retro-term state=pseudo_tiled

# bspc desktop '^3' -l monocle
